spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/springbootdb
    username: 
    password:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/springbootdb
    user: 
    password:
