spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootdb
    driver-class-name: org.postgresql.Driver
    username: 
    password:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml