spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/springbootdb
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/springbootdb
    user: postgres
    password: postgres
